repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: black
        args: [--config, project/pyproject.toml]

  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.7.5"
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        args: [-i, --config, project/pyproject.toml]
        language: python
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.2"
    hooks:
      - id: ruff
        name: ruff
        args: [--config, project/pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: [--sp, project/pyproject.toml]
